config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'

  get 'comments/update'

  get 'comments/destroy'

  get 'landing/index'
  resources :articles
  resources :categories do
    resources :articles do
      resources :comments
    end
  end

  resources :users do
    resources :articles
  end

  root 'landing#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
validates_presence_of :title, :body
belongs_to :user
has_and_belongs_to_many  :categories
has_many :comments

scope :published, lambda { where('articles.published_at IS NOT NULL')}
scope :draft, -> { where('articles.published_at IS NULL') }
scope :recent, lambda { where('articles.published_at > ?',1.week.ago.to_date)}
scope :where_title, lambda {|term| where('articles.title LIKE ?',"%#{term}%") }
scope :uncategorized, lambda { joins('LEFT JOIN articles_categories ON articles.id=articles_categories.article_id').where('articles_categories.category_id IS NULL')    }

  def long_title
    "#{title} - #{published_at}"
  end


end

app/models/category.rb
class Category < ActiveRecord::Base
has_and_belongs_to_many :articles
validates_presence_of :name
validates_uniqueness_of :name
default_scope lambda { order('categories.name') }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
 belongs_to :article

 def after_create
  puts "send an email....."
 end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password

  validates_uniqueness_of :email
  validates_length_of :email, within: 0..50
  validates_format_of :email , with: /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i, :multiline => true
  validates_confirmation_of :password, :if => :password_required?

  has_one :profile, :dependent => :destroy
  has_many :articles,  :dependent => :nullify
  has_many :replies, :through => :articles, :source => :comments


  default_scope lambda {  order('users.name') }


  before_save :set_encrypted_password




  def self.authenticate(email ,password )
  user = User.find_by_email(email)
  return user if user && ( encrypt(password) == user.hashed_password )
  end

  def authenticated?(pass)
    self.hashed_password == encrypt(pass)
  end

  def highly_liked_article
    self.articles.order('articles.likes DESC').first
  end


  protected

  def set_encrypted_password
    puts name
    return if password.blank?
    self.hashed_password = encrypt(password)
  end

  def encrypt(str)
      Digest::SHA1.hexdigest(str)
  end

  def password_required?
    hashed_password.blank? || password.present?
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  layout 'basic'
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    unless params[:user_id].nil?
      @articles = @articles.where(:user_id => params[:user_id])
    end
    if params[:uncat].present?
      @articles = @articles.joins('LEFT JOIN articles_categories ON articles.id=articles_categories.article_id').where('articles_categories.category_id IS NULL');
    end
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        @article.categories << Category.find_by_id(params[:category]) unless (params[:category] == '0')
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :location, :excerpt, :body, :published_at)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  layout 'basic'
  def index
  end

  def show
    @category = Category.includes(:articles).find_by_id(params[:id])
  end


  def create

  end

  def new
  end

  def edit
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def create
    @comment = Article.find_by_id(params[:article_id]).comments.create!({ body: params[:body], name: params[:name], email: params[:email]}) rescue nil
    @comment.save
    respond_to do |format|
      format.js
    end
  end


  def update

  end

  def destroy

  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  layout 'basic'
  def index
    @users = User.all
    @categories = Category.includes(:articles)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/articles/_articles_listing.erb
<table>
  <thead>
  <tr>
    <th>Title</th>
  </tr>
  </thead>

  <tbody>
  <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.long_title,article_path(article) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="field">
       <%= label_tag :category , 'Category' %><br/>
      <%= select_tag :category, options_for_select(Category.all.map{ |c| [c.name, c.id]} << ['Uncat',0], 0 )%>
    </div>


    <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>


  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :excerpt %><br>
    <%= f.text_field :excerpt %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.datetime_select :published_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= render partial: "articles/articles_listing", object: @articles %>
<br>
<%= link_to 'New Article', new_article_path %>

app/views/articles/index.js.erb
$("#cat_table").html("<%= escape_javascript(render :partial => 'articles_listing') %>");

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% content_for :back do %>
    <%= link_to "Back", :back  %>
<% end %>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @article.location %>
</p>

<p>
  <strong>Excerpt:</strong>
  <%= @article.excerpt %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @article.published_at %>
</p>


<p>
  <strong>Comments:</strong><br/>
  <% if  @article.comments.empty? %>
   <ul id="comments"><li>
     No comments !!!
   </li>
     <li>
       <%= form_tag("/comments/create?article_id=#{@article.id}", method: 'get', :remote => true) do %>
           <%= label_tag :body, "Comment:" %>
           <%= text_field_tag :body  %>
           <%= label_tag :name, "By:" %>
           <%= text_field_tag :name %>
           <%= label_tag :email, "Email:" %>
           <%= text_field_tag :email %>
           <%= submit_tag "Add Comment.." %>
       <% end %>
     </li>
   </ul>
  <% else %>
     <ul id="comments">
      <% @article.comments.each do |com| %>
      <% next if com.body.nil? %>
      <li>
        <%= (com.body + "... by #{com.name.empty? ? 'Anonymous' : com.name }")  %>
      </li>
      <% end %>
       <li>
         <%= form_tag("/comments/create?article_id=#{@article.id}", method: 'get', :remote => true) do %>
             <%= label_tag :body, "Comment:" %>
             <%= text_field_tag :body  %>
             <%= label_tag :name, "By:" %>
             <%= text_field_tag :name %>
             <%= label_tag :email, "Email:" %>
             <%= text_field_tag :email %>
             <%= submit_tag "Add Comment.." %>
       <% end %>
        </li>
     </ul>
  <% end %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/categories/show.html.erb
<% content_for :back do %>
<%= link_to "Back", :back  %>
<% end %>
<table class="table table-hover">
  <thead>
  <th><%= @category.name %></th>
  </thead>
  <tbody>
  <% @category.articles.each do |art| %>
      <tr>
        <td>
          <%= link_to "#{art.title}", category_article_path(@category, art) %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/comments/create.js.erb
my_from = $("#comments").find('li:last').html();
$("#comments").find('li:last').remove();
$("#comments").append("<li><%= (@comment.body + "... by #{@comment.name.empty? ? 'Anonymous' : @comment.name }")  %></li>");
$("#comments").append("<li>"+ my_from + "</li>");

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/landing/index.html.erb
<table class="table table-hover" id="cat_table">
<thead>
  <th>Category Name</th>
</thead>
  <tbody>
  <% @categories.each do |cat| %>
  <tr>
    <td>
     <%= link_to "#{cat.name} (#{cat.articles.count})", category_path(cat) %>
    </td>
  </tr>
      <% end %>
  <tr>
    <td>
      <%= link_to "Un-Categorized  (#{ Article.uncategorized.count }) " , articles_path(uncat: true) , remote: true %>
    </td>
  </tr>
  </tbody>
</table>


    <table class="table table-hover" id="user_table">
      <thead>
      <th>User Name</th>
      <th>User Email</th>
      </thead>
      <tbody>
      <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to "All Artilces by #{(user.name.blank? ? 'Anonymous': user.name)}", articles_path, remote: true   %>
        </td>
        <td>
          <%= link_to "Highly liked article by #{(user.name.blank? ? 'Anonymous': user.name)}", article_path(user.highly_liked_article), remote: true  %>
        </td>
        <td>
          <%= user.email %>
        </td>
      </tr>
          <% end %>
      </tbody>
    </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/basic.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">Maviz Cheema Blog !!!</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link", '#'  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield(:back) %>
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Quick Actions</li>
              <li><%= link_to "Add new article", new_article_path  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>